version: "3"
services:
  portal:
    image: f5devcentral/f5-openstack-services:portal-latest
    container_name: PORTAL
    env_file:
      - ./appcluster.rc
    ports:
      - 8245:80
    depends_on:
      - FLUENTD
#    logging:
#      driver: fluentd
#      options:
#        fluentd-address: "0.0.0.0:24224"
#        tag: f5-portal

  wafaas:
    image: f5devcentral/f5-openstack-services:adcaas-latest
    container_name: WAFAAS
    env_file:
      - ./appcluster.rc
    ports:
      - ${WAF_APP_PORT:-3000}:3000
    depends_on:
      - postgres
      - ASG
      - DO
      - FLUENTD
    links:
      - postgres:postgres-server
      - ASG:asg-server
      - DO:do-server
    volumes:
      - ${DEPENDENCIES_DIRECTORY}:/var/dependencies
      - ${DATA_DIRECTORY}:/var/data
    logging:
      driver: fluentd
      options:
        fluentd-address: "0.0.0.0:24224"
        tag: f5-wafaas

  postgres:
    image: postgres:11.1
    container_name: POSTGRES
    environment:
      - POSTGRES_USER=${DATABASE_USER:-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-postgres}
      - POSTGRES_DB=${DATABASE_DB:-postgres}
    ports:
      - ${DATABASE_PORT:-5432}:5432
    volumes:
      - ${DATABASE_DATA_DIRECTORY}:/var/lib/postgresql/data
    depends_on:
      - FLUENTD
    logging:
      driver: fluentd
      options:
        fluentd-address: "0.0.0.0:24224"
        tag: postgres

  ASG:
    image: f5devcentral/f5-api-services-gateway:latest
    container_name: ASG
    environment:
      - AUTH=DISABLE
    ports:
      - 8443:443
      - 8080:80
    volumes:
      - ${DEPENDENCIES_DIRECTORY}:/var/dependencies
      - ${ASG_EXTENSIONS_DIRECTORY}:/root/lx
      - ${ASG_DATA_DIRECTORY}:/var/config
    depends_on:
      - FLUENTD
    logging:
      driver: fluentd
      options:
        fluentd-address: "0.0.0.0:24224"
        tag: f5-asg

  DO:
    image: f5devcentral/f5-do-container:1.5.0
    container_name: DO
    ports:
      - 9443:443
      - 8081:80
    depends_on:
      - FLUENTD
    logging:
      driver: fluentd
      options:
        fluentd-address: "0.0.0.0:24224"
        tag: f5-do

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: ELASTICSEARCH
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node

  FLUENTD:
    image: f5devcentral/f5-openstack-services:fluentd-v1.3.2
    container_name: FLUENTD
    ports:
      - 24224:24224
      - 24224:24224/udp
      - 20001:20001/udp
    volumes:
      - ./fluentd.conf:/fluentd/etc/fluentd.conf
    depends_on:
      - elasticsearch
      - kibana
    environment:
      - FLUENTD_CONF=fluentd.conf

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    container_name: KIBANA
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    expose:
      - 5601
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
# networks:
#   app_net:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#       - subnet: ${WAF_APP_NETWORK-172.16.238.0/24}

